In [47]:
import pandas as pd
import numpy as np

# Data preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

# Data split
from sklearn.model_selection import train_test_split

# Data exploration

In this section I will be exploring the dataset in regards of different aspects such as the completeness, the data type, and more. This will guide me in the data cleaning process

In [16]:
# Loading the data
policies = pd.read_csv("../data/home_insurance.csv")

In [5]:
# Analyzing each of the variables in the dataset
policies.describe(include="all")

,QUOTE_DATE,COVER_START,CLAIM3YEARS,P1_EMP_STATUS,P1_PT_EMP_STATUS,BUS_USE,CLERICAL,AD_BUILDINGS,RISK_RATED_AREA_B,SUM_INSURED_BUILDINGS,...,HP3_ADDON_PRE_REN,HP3_ADDON_POST_REN,MTA_FLAG,MTA_FAP,MTA_APRP,MTA_DATE,LAST_ANN_PREM_GROSS,POL_STATUS,i,Police
count,129524,189021,190039,189021,1782,189021,2944,189021,140876.000000,189021.000000,...,189021,189021,190039,55720.000000,55720.000000,26575,190039.000000,189021,256136.000000,256136
unique,1260,2207,2,11,9,2,2,2,NaN,NaN,...,2,2,2,NaN,NaN,1287,NaN,4,NaN,256136
top,1/9/2012,01/03/2011,N,R,E,N,Y,Y,NaN,NaN,...,N,N,N,NaN,NaN,01/02/2010,NaN,Live,NaN,P108635
freq,694,3510,168088,146621,1259,186077,2644,147259,NaN,NaN,...,189005,188395,134319,NaN,NaN,316,NaN,132160,NaN,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.274440,778130.472276,...,NaN,NaN,NaN,200.938091,90.613137,NaN,186.841196,NaN,128068.500000,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.449942,415504.938301,...,NaN,NaN,NaN,107.947457,122.043969,NaN,99.516851,NaN,73940.238612,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,...,NaN,NaN,NaN,-1152.680000,-423.080000,NaN,-1152.680000,NaN,1.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,1000000.000000,...,NaN,NaN,NaN,137.410000,0.000000,NaN,123.580000,NaN,64034.750000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000,1000000.000000,...,NaN,NaN,NaN,189.035000,0.000000,NaN,177.390000,NaN,128068.500000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.000000,1000000.000000,...,NaN,NaN,NaN,248.920000,180.902500,NaN,235.090000,NaN,192102.250000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.000000,1000000.000000,...,NaN,NaN,NaN,4631.860000,1449.240000,NaN,4631.860000,NaN,256136.000000,NaN

In [6]:
# Data type and missing values
policies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256136 entries, 0 to 256135
Data columns (total 66 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   QUOTE_DATE              129524 non-null  object
 1   COVER_START             189021 non-null  object
 2   CLAIM3YEARS             190039 non-null  object
 3   P1_EMP_STATUS           189021 non-null  object
 4   P1_PT_EMP_STATUS        1782 non-null    object
 5   BUS_USE                 189021 non-null  object
 6   CLERICAL                2944 non-null    object
 7   AD_BUILDINGS            189021 non-null  object
 8   RISK_RATED_AREA_B       140876 non-null  float64
 9   SUM_INSURED_BUILDINGS   189021 non-null  float64
 10  NCD_GRANTED_YEARS_B     189021 non-null  float64
 11  AD_CONTENTS             189021 non-null  object
 12  RISK_RATED_AREA_C       180290 non-null  float64
 13  SUM_INSURED_CONTENTS    189021 non-null  float64
 14  NCD_GRANTED_YEARS_C     189021 non-null  float64
 15  CONTENTS_COVER          189021 non-null  object
 16  BUILDINGS_COVER         189021 non-null  object
 17  SPEC_SUM_INSURED        189021 non-null  float64
 18  SPEC_ITEM_PREM          189021 non-null  float64
 19  UNSPEC_HRP_PREM         189021 non-null  float64
 20  P1_DOB                  189021 non-null  object
 21  P1_MAR_STATUS           189021 non-null  object
 22  P1_POLICY_REFUSED       189021 non-null  object
 23  P1_SEX                  189021 non-null  object
 24  APPR_ALARM              189021 non-null  object
 25  APPR_LOCKS              189021 non-null  object
 26  BEDROOMS                189021 non-null  float64
 27  ROOF_CONSTRUCTION       189021 non-null  float64
 28  WALL_CONSTRUCTION       189021 non-null  float64
 29  FLOODING                189021 non-null  object
 30  LISTED                  189021 non-null  float64
 31  MAX_DAYS_UNOCC          189021 non-null  float64
 32  NEIGH_WATCH             189021 non-null  object
 33  OCC_STATUS              189021 non-null  object
 34  OWNERSHIP_TYPE          189021 non-null  float64
 35  PAYING_GUESTS           189021 non-null  float64
 36  PROP_TYPE               189021 non-null  float64
 37  SAFE_INSTALLED          189021 non-null  object
 38  SEC_DISC_REQ            189021 non-null  object
 39  SUBSIDENCE              189021 non-null  object
 40  YEARBUILT               189021 non-null  float64
 41  CAMPAIGN_DESC           0 non-null       float64
 42  PAYMENT_METHOD          189021 non-null  object
 43  PAYMENT_FREQUENCY       80554 non-null   float64
 44  LEGAL_ADDON_PRE_REN     189021 non-null  object
 45  LEGAL_ADDON_POST_REN    189021 non-null  object
 46  HOME_EM_ADDON_PRE_REN   189021 non-null  object
 47  HOME_EM_ADDON_POST_REN  189021 non-null  object
 48  GARDEN_ADDON_PRE_REN    189021 non-null  object
 49  GARDEN_ADDON_POST_REN   189021 non-null  object
 50  KEYCARE_ADDON_PRE_REN   189021 non-null  object
 51  KEYCARE_ADDON_POST_REN  189021 non-null  object
 52  HP1_ADDON_PRE_REN       189021 non-null  object
 53  HP1_ADDON_POST_REN      189021 non-null  object
 54  HP2_ADDON_PRE_REN       189021 non-null  object
 55  HP2_ADDON_POST_REN      189021 non-null  object
 56  HP3_ADDON_PRE_REN       189021 non-null  object
 57  HP3_ADDON_POST_REN      189021 non-null  object
 58  MTA_FLAG                190039 non-null  object
 59  MTA_FAP                 55720 non-null   float64
 60  MTA_APRP                55720 non-null   float64
 61  MTA_DATE                26575 non-null   object
 62  LAST_ANN_PREM_GROSS     190039 non-null  float64
 63  POL_STATUS              189021 non-null  object
 64  i                       256136 non-null  int64
 65  Police                  256136 non-null  object
dtypes: float64(23), int64(1), object(42)
memory usage: 129.0+ MB

In [49]:
policies.columns

Index(['QUOTE_DATE', 'COVER_START', 'CLAIM3YEARS', 'P1_EMP_STATUS',
       'P1_PT_EMP_STATUS', 'BUS_USE', 'CLERICAL', 'AD_BUILDINGS',
       'RISK_RATED_AREA_B', 'SUM_INSURED_BUILDINGS', 'NCD_GRANTED_YEARS_B',
       'AD_CONTENTS', 'RISK_RATED_AREA_C', 'SUM_INSURED_CONTENTS',
       'NCD_GRANTED_YEARS_C', 'CONTENTS_COVER', 'BUILDINGS_COVER',
       'SPEC_SUM_INSURED', 'SPEC_ITEM_PREM', 'UNSPEC_HRP_PREM', 'P1_DOB',
       'P1_MAR_STATUS', 'P1_POLICY_REFUSED', 'P1_SEX', 'APPR_ALARM',
       'APPR_LOCKS', 'BEDROOMS', 'ROOF_CONSTRUCTION', 'WALL_CONSTRUCTION',
       'FLOODING', 'LISTED', 'MAX_DAYS_UNOCC', 'NEIGH_WATCH', 'OCC_STATUS',
       'OWNERSHIP_TYPE', 'PAYING_GUESTS', 'PROP_TYPE', 'SAFE_INSTALLED',
       'SEC_DISC_REQ', 'SUBSIDENCE', 'YEARBUILT', 'CAMPAIGN_DESC',
       'PAYMENT_METHOD', 'PAYMENT_FREQUENCY', 'LEGAL_ADDON_PRE_REN',
       'LEGAL_ADDON_POST_REN', 'HOME_EM_ADDON_PRE_REN',
       'HOME_EM_ADDON_POST_REN', 'GARDEN_ADDON_PRE_REN',
       'GARDEN_ADDON_POST_REN', 'KEYCARE_ADDON_PRE_REN',
       'KEYCARE_ADDON_POST_REN', 'HP1_ADDON_PRE_REN', 'HP1_ADDON_POST_REN',
       'HP2_ADDON_PRE_REN', 'HP2_ADDON_POST_REN', 'HP3_ADDON_PRE_REN',
       'HP3_ADDON_POST_REN', 'MTA_FLAG', 'MTA_FAP', 'MTA_APRP', 'MTA_DATE',
       'LAST_ANN_PREM_GROSS', 'POL_STATUS', 'i', 'Police', 'CLAIM'],
      dtype='object')

## Variable Exploration

This section will help me learning about the target and the different variables the data has

In [57]:
categorical_features = ['P1_EMP_STATUS',
       'P1_PT_EMP_STATUS', 'BUS_USE', 'CLERICAL', 'AD_BUILDINGS',
       'AD_CONTENTS', 'NCD_GRANTED_YEARS_C', 'CONTENTS_COVER', 'BUILDINGS_COVER',
       'P1_MAR_STATUS', 'P1_POLICY_REFUSED', 'P1_SEX', 'APPR_ALARM',
       'APPR_LOCKS', 'BEDROOMS', 'ROOF_CONSTRUCTION', 'WALL_CONSTRUCTION',
       'FLOODING', 'LISTED', 'MAX_DAYS_UNOCC', 'NEIGH_WATCH', 'OCC_STATUS',
       'OWNERSHIP_TYPE', 'PAYING_GUESTS', 'PROP_TYPE', 'SAFE_INSTALLED',
       'SEC_DISC_REQ', 'SUBSIDENCE', 'YEARBUILT', 'CAMPAIGN_DESC',
       'PAYMENT_METHOD', 'PAYMENT_FREQUENCY', 'LEGAL_ADDON_PRE_REN',
       'LEGAL_ADDON_POST_REN', 'HOME_EM_ADDON_PRE_REN',
       'HOME_EM_ADDON_POST_REN', 'GARDEN_ADDON_PRE_REN',
       'GARDEN_ADDON_POST_REN', 'KEYCARE_ADDON_PRE_REN',
       'KEYCARE_ADDON_POST_REN', 'HP1_ADDON_PRE_REN', 'HP1_ADDON_POST_REN',
       'HP2_ADDON_PRE_REN', 'HP2_ADDON_POST_REN', 'HP3_ADDON_PRE_REN',
       'HP3_ADDON_POST_REN', 'MTA_FLAG','POL_STATUS']

In [51]:
# This section counts the number of observations per level of each variable
for feat in categorical_features + ['CLAIM3YEARS']:
    print('Feature: %s' %(feat))
    print('------------')
    print(policies[feat].value_counts())
    print('\n\n')

Feature: P1_EMP_STATUS
------------
R    146621
E     36398
S      3065
H      1069
U       921
N       754
V        68
A        52
F        29
I        28
C        16
Name: P1_EMP_STATUS, dtype: int64



Feature: P1_PT_EMP_STATUS
------------
E    1259
S     246
V     224
R      36
C      11
U       2
I       2
F       1
H       1
Name: P1_PT_EMP_STATUS, dtype: int64



Feature: BUS_USE
------------
N    186077
Y      2944
Name: BUS_USE, dtype: int64



Feature: CLERICAL
------------
Y    2644
N     300
Name: CLERICAL, dtype: int64



Feature: AD_BUILDINGS
------------
Y    147259
N     41762
Name: AD_BUILDINGS, dtype: int64



Feature: AD_CONTENTS
------------
Y    180452
N      8569
Name: AD_CONTENTS, dtype: int64



Feature: NCD_GRANTED_YEARS_C
------------
6.0    110765
7.0     31788
5.0     12946
3.0     11899
0.0     10490
4.0      3840
2.0      2759
9.0      2640
1.0      1173
8.0       721
Name: NCD_GRANTED_YEARS_C, dtype: int64



Feature: CONTENTS_COVER
------------
Y    147259
N     41762
Name: CONTENTS_COVER, dtype: int64



Feature: BUILDINGS_COVER
------------
Y    180452
N      8569
Name: BUILDINGS_COVER, dtype: int64



Feature: P1_MAR_STATUS
------------
M    66474
P    44148
O    33061
W    25513
S    10270
D     7882
A     1070
C      544
B       32
N       27
Name: P1_MAR_STATUS, dtype: int64



Feature: P1_POLICY_REFUSED
------------
N    188958
Y        63
Name: P1_POLICY_REFUSED, dtype: int64



Feature: P1_SEX
------------
M    103003
F     85930
N        88
Name: P1_SEX, dtype: int64



Feature: APPR_ALARM
------------
N    174925
Y     14096
Name: APPR_ALARM, dtype: int64



Feature: APPR_LOCKS
------------
Y    133924
N     55097
Name: APPR_LOCKS, dtype: int64



Feature: BEDROOMS
------------
3.0    98851
2.0    52971
4.0    23994
1.0     9806
5.0     3264
6.0      118
7.0       17
Name: BEDROOMS, dtype: int64



Feature: ROOF_CONSTRUCTION
------------
11.0    187840
19.0       669
4.0        157
2.0         97
7.0         85
15.0        49
5.0         37
10.0        25
9.0         13
3.0         11
99.0        11
16.0        10
8.0          7
14.0         7
12.0         1
18.0         1
6.0          1
Name: ROOF_CONSTRUCTION, dtype: int64



Feature: WALL_CONSTRUCTION
------------
15.0    188066
3.0        371
19.0       154
16.0        79
14.0        76
5.0         64
11.0        52
4.0         35
18.0        29
20.0        25
9.0         20
2.0         11
21.0        10
99.0        10
23.0         9
22.0         4
12.0         3
1.0          2
6.0          1
Name: WALL_CONSTRUCTION, dtype: int64



Feature: FLOODING
------------
Y    185121
N      3900
Name: FLOODING, dtype: int64



Feature: LISTED
------------
3.0    187933
2.0       933
4.0        75
5.0        50
1.0        30
Name: LISTED, dtype: int64



Feature: MAX_DAYS_UNOCC
------------
0.0      137443
30.0      51171
181.0       299
90.0         70
180.0        20
120.0        17
60.0          1
Name: MAX_DAYS_UNOCC, dtype: int64



Feature: NEIGH_WATCH
------------
N    144044
Y     44977
Name: NEIGH_WATCH, dtype: int64



Feature: OCC_STATUS
------------
PH    188211
LP       606
HH       124
UN        72
WD         4
OT         2
WE         2
Name: OCC_STATUS, dtype: int64



Feature: OWNERSHIP_TYPE
------------
8.0     149755
3.0      27388
12.0      4688
18.0      3647
14.0      2610
2.0        416
7.0        158
11.0       118
13.0       109
17.0        83
16.0        28
6.0         12
1.0          5
15.0         4
Name: OWNERSHIP_TYPE, dtype: int64



Feature: PAYING_GUESTS
------------
0.0    188814
1.0       207
Name: PAYING_GUESTS, dtype: int64



Feature: PROP_TYPE
------------
10.0    55230
2.0     32089
1.0     29776
19.0    28948
9.0     16224
18.0     6362
25.0     5924
7.0      5767
26.0     2535
48.0     1803
51.0      678
4.0       631
17.0      625
32.0      557
16.0      359
53.0      320
45.0      315
47.0      312
52.0      114
31.0       93
22.0       66
40.0       51
29.0       28
20.0       27
27.0       27
30.0       25
37.0       23
3.0        23
44.0       21
21.0       20
39.0       16
24.0       14
38.0        8
28.0        5
23.0        4
8.0         1
Name: PROP_TYPE, dtype: int64



Feature: SAFE_INSTALLED
------------
N    187418
Y      1603
Name: SAFE_INSTALLED, dtype: int64



Feature: SEC_DISC_REQ
------------
Y    145564
N     43457
Name: SEC_DISC_REQ, dtype: int64



Feature: SUBSIDENCE
------------
N    187785
Y      1236
Name: SUBSIDENCE, dtype: int64



Feature: YEARBUILT
------------
1946.0    64831
1920.0    33679
1960.0    31287
1980.0    28057
1900.0    15687
1990.0     5692
2000.0     4136
1870.0     2835
1869.0     2564
1749.0      222
1871.0       11
1750.0        6
1950.0        4
1930.0        4
1995.0        3
1970.0        2
1910.0        1
Name: YEARBUILT, dtype: int64



Feature: CAMPAIGN_DESC
------------
Series([], Name: CAMPAIGN_DESC, dtype: int64)



Feature: PAYMENT_METHOD
------------
NonDD       95065
PureDD      85619
DD-Other     8337
Name: PAYMENT_METHOD, dtype: int64



Feature: PAYMENT_FREQUENCY
------------
1.0    80554
Name: PAYMENT_FREQUENCY, dtype: int64



Feature: LEGAL_ADDON_PRE_REN
------------
Y    114487
N     74534
Name: LEGAL_ADDON_PRE_REN, dtype: int64



Feature: LEGAL_ADDON_POST_REN
------------
Y    105855
N     83166
Name: LEGAL_ADDON_POST_REN, dtype: int64



Feature: HOME_EM_ADDON_PRE_REN
------------
N    136183
Y     52838
Name: HOME_EM_ADDON_PRE_REN, dtype: int64



Feature: HOME_EM_ADDON_POST_REN
------------
N    179821
Y      9200
Name: HOME_EM_ADDON_POST_REN, dtype: int64



Feature: GARDEN_ADDON_PRE_REN
------------
N    174118
Y     14903
Name: GARDEN_ADDON_PRE_REN, dtype: int64



Feature: GARDEN_ADDON_POST_REN
------------
N    175488
Y     13533
Name: GARDEN_ADDON_POST_REN, dtype: int64



Feature: KEYCARE_ADDON_PRE_REN
------------
N    180122
Y      8899
Name: KEYCARE_ADDON_PRE_REN, dtype: int64



Feature: KEYCARE_ADDON_POST_REN
------------
N    179362
Y      9659
Name: KEYCARE_ADDON_POST_REN, dtype: int64



Feature: HP1_ADDON_PRE_REN
------------
N    188980
Y        41
Name: HP1_ADDON_PRE_REN, dtype: int64



Feature: HP1_ADDON_POST_REN
------------
N    186570
Y      2451
Name: HP1_ADDON_POST_REN, dtype: int64



Feature: HP2_ADDON_PRE_REN
------------
N    188811
Y       210
Name: HP2_ADDON_PRE_REN, dtype: int64



Feature: HP2_ADDON_POST_REN
------------
N    153694
Y     35327
Name: HP2_ADDON_POST_REN, dtype: int64



Feature: HP3_ADDON_PRE_REN
------------
N    189005
Y        16
Name: HP3_ADDON_PRE_REN, dtype: int64



Feature: HP3_ADDON_POST_REN
------------
N    188395
Y       626
Name: HP3_ADDON_POST_REN, dtype: int64



Feature: MTA_FLAG
------------
N    134319
Y     55720
Name: MTA_FLAG, dtype: int64



Feature: POL_STATUS
------------
Live         132160
Lapsed        52534
Cancelled      4311
Unknown          16
Name: POL_STATUS, dtype: int64



Feature: CLAIM3YEARS
------------
N    168088
Y     21951
Name: CLAIM3YEARS, dtype: int64

## Data cleaning

Once all the variables were looked in more detail, I will clean the data

In [96]:
# This section converts the bi-level variable into a binary one so it is easier to model
conditions = [policies['CLAIM3YEARS'] == 'Y', 
              policies['CLAIM3YEARS'] == 'N']

choices = [1, 0]

policies['CLAIM'] = np.select(conditions, choices, default=0)

# I am only going to use live policies, because lapsed and cancelled policies may affect the index
policies_final = policies.query("POL_STATUS == 'Live'")

# Dropping the response to avoid redundancy
policies_final = policies_final.drop(columns = ['CLAIM3YEARS'])

In [97]:
policies_final.head()

,QUOTE_DATE,COVER_START,P1_EMP_STATUS,P1_PT_EMP_STATUS,BUS_USE,CLERICAL,AD_BUILDINGS,RISK_RATED_AREA_B,SUM_INSURED_BUILDINGS,NCD_GRANTED_YEARS_B,...,HP3_ADDON_POST_REN,MTA_FLAG,MTA_FAP,MTA_APRP,MTA_DATE,LAST_ANN_PREM_GROSS,POL_STATUS,i,Police,CLAIM
1,11/22/2007,01/01/2008,E,NaN,Y,N,Y,25.0,1000000.0,6.0,...,N,Y,308.83,-9.27,NaN,308.83,Live,2,P000002,0
2,11/23/2007,23/11/2007,E,NaN,N,NaN,N,NaN,0.0,0.0,...,N,Y,52.65,52.65,03/11/2010,52.65,Live,3,P000003,0
3,11/23/2007,12/12/2007,R,NaN,N,NaN,N,NaN,0.0,0.0,...,N,N,NaN,NaN,NaN,54.23,Live,4,P000004,0
4,11/22/2007,15/12/2007,R,NaN,N,NaN,Y,5.0,1000000.0,7.0,...,N,N,NaN,NaN,NaN,244.58,Live,5,P000005,0
5,11/22/2007,01/12/2007,R,NaN,N,NaN,N,NaN,0.0,0.0,...,N,N,NaN,NaN,NaN,51.45,Live,6,P000006,0

In [98]:
length_policies = len(policies_final["CLAIM"])
print(f"I will work with {length_policies} policies")

I will work with 132160 policies

In [99]:
target = ['CLAIM']
policies_final = policies_final.loc[:,numeric_features+categorical_features+target]

policies_final.loc[:,numeric_features] = policies_final.loc[:,numeric_features].fillna(0)
policies_final.loc[:,categorical_features] = policies_final.loc[:,categorical_features].fillna('MV')

In [100]:
policies_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 132160 entries, 1 to 256135
Data columns (total 5 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   SUM_INSURED_BUILDINGS  132160 non-null  float64
 1   SUM_INSURED_CONTENTS   132160 non-null  float64
 2   BUS_USE                132160 non-null  object
 3   CLERICAL               132160 non-null  object
 4   CLAIM                  132160 non-null  int32
dtypes: float64(2), int32(1), object(2)
memory usage: 5.5+ MB

In [101]:
# I am using a train-test split of 70%
train, test = train_test_split(policies_final, train_size = 0.7, random_state = 1234)
y_train = train['CLAIM']
y_test = test['CLAIM']

# Preprocessing

In [102]:
# For this part I am turning the categorical variables into dummy variables and the numeric variables
# into a normal distribution

categorical_features = ['BUS_USE', 'CLERICAL']
numeric_features = ['SUM_INSURED_BUILDINGS',
                   'SUM_INSURED_CONTENTS']

preprocessor = ColumnTransformer(
    transformers=[
        ('scale', StandardScaler(), numeric_features),
        ('ohe', OneHotEncoder(drop="first"), categorical_features)])

In [103]:
train = pd.DataFrame(preprocessor.fit_transform(train),
                       index=train.index,
                       columns=(numeric_features +
                                list(preprocessor.named_transformers_['ohe']
                                     .get_feature_names(categorical_features))))


test = pd.DataFrame(preprocessor.transform(test),
                      index=test.index,
                      columns=X_train.columns)

train['CLAIM'] = y_train
test['CLAIM'] = y_test

In [106]:
# Printing the data
train.to_csv("../data/processed_data/home_train.csv")
test.to_csv("../data/processed_data/home_test.csv")